### ISSUE TITLE
Edges are incorrectly updated after changing notation

### ISSUE THREAD

**Issue by Aksem** [borkdominik/bigER#19]
**How to reproduce:** change notation from 'Default' to 'Bachman' and back.

**What is wrong:** edges are either incorrect or even invisible. After moving a diagram element that forces edge update, they are correct again.

Incorrect after changing:
![grafik](https://user-images.githubusercontent.com/5513768/179704176-34709c7d-6614-41ae-85a5-9a7f103c217c.png)

Correct after force update:
![grafik](https://user-images.githubusercontent.com/5513768/179704260-6e1bfec2-110f-454b-bd19-bf5b4df065c4.png)

**Comment by Aksem** [comment]
Found the reason and described in adaptagrams issue: https://github.com/Aksem/adaptagrams/issues/11

Briefly about the problem: after changing the notation, old edges are removed, and new ones with the new notation are created. If new edges are created first and only after that the old ones are removed, libavoid doesn't update edges, and they look so as if there are both new and old edges.

Fixed in adaptagrams: https://github.com/Aksem/adaptagrams/pull/12
And released new libavoid-js, sprotty-routing-libavoid and updated them in bigER.

**Comment by plglaser** [comment]
I reopened the issue because there are still problems with edges disappearing on changes in the model. It seems that not all types of changes lead to the bug. 




**Steps to reproduce**

1. Use the following model and open the diagram
```
erdiagram Example

entity A { id key }
entity B { id key }
relationship Rel { A[1] -> B[N] }
```
2. In the textual editor, change the cardinalities in the relationship, e.g., from `B[N]`to `B[1]`.
3. **See Error** ➜ Edges do not get rendered

<img width="400" alt="diagram with error" src="https://user-images.githubusercontent.com/39776671/183143512-cf278c06-f742-4e46-a051-7fa2d3509858.png">

The dev tools also show *"Cannot compute route"*:

<img width="500" alt="dev tools" src="https://user-images.githubusercontent.com/39776671/183144796-f9bd0d34-87f7-4480-ac21-8d6dd6306a99.png">
