### ISSUE TITLE
Warning on Java 11

### ISSUE THREAD

**Issue by tommccallum** [borkdominik/bigER#3]
First off, great work this is a really useful tool that I will be using at our university to help our students.

I got this warning on Fedora 32, Java 11, VS Code:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/tom/.vscode/extensions/bigmodelingtools.erdiagram-0.0.2/server/erdiagram-language-server/lib/guice-3.0.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[Warn  - 09:25:33] Model requests are not supported by the Xtext diagram server.

$ java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment 18.9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9, mixed mode, sharing)

$ code -v
1.61.2
6cba118ac49a1b88332f312a8f67186f7f3c1643
x64

This is why I think when I try and use with the latest openjdk it also fails.

**Comment by plglaser** [comment]
I recently updated the tool including some changes dealing with this issue. The tool should now be available for later JDK versions and the `"[Warn - 09:25:33] Model requests are not supported by the Xtext diagram server."` - message should not appear anymore. 

Could you try again with the latest version [from the marketplace](https://marketplace.visualstudio.com/items?itemName=BIGModelingTools.erdiagram) (v0.0.3) and report back any issues?

Using the tool with JDK 17+ could still be a problem and the `reflective access` warnings might still appear, due to an [old guice version](https://github.com/google/guice/issues/1133). As far as I can tell, this is coming from Xtext and it seems the [newest version fixes](https://github.com/eclipse/xtext-core/issues/393) this. I will try updating to the newest version, in a future release.

**Comment by plglaser** [comment]
Updated to a newer Xtext version which closes this issue.

Feel free to open the issue again if you still encounter any problems.
