### ISSUE TITLE
EdgeLayoutProcessor ignored during initial layout

### ISSUE THREAD

**Issue by plglaser** [borkdominik/bigER#48]
### Description

When opening the diagram for the first time, the labels on edges are not properly laid out. Take the following model for example:
```
erdiagram Model

entity Ex1 { id key }
entity Ex2 { id key }

relationship Rel {
    Ex1[1] -> Ex2[ N | "roleeeeeeee" ]
}
```
The corresponding, invalid diagram is shown below (see *Current Behavior* and note the layout of the "longer" role for `Ex2` in the relationship), right when opening the diagram initially.

After making changes to the model or refreshing the diagram, the automatic layout is fixed again and behaves as expected (see *Expected Behavior*).

### Current Behavior

_Invalid Layout:_
<img width="500" alt="Invalid Diagram Layout" src="https://user-images.githubusercontent.com/39776671/208247745-e2517a96-f137-454b-ade0-98816ea8e989.png">

### Expected Behavior

_Valid Layout:_
<img width="500" alt="Valid Diagram Layout" src="https://user-images.githubusercontent.com/39776671/208247827-c41fd37a-7237-4daa-8ba6-6256bbfc1b52.png">

### Steps to Reproduce

1. Specify an ER model containing a "long" edge label (see Example)
2. Open the diagram
3. --> See incorrect Layout

### Environment

Issue starts occurring in the recent releases (v0.2.0+) of bigER. 

### Additional Information

The problem seems related to the [`BigerEdgeLayoutPostprocessor`](https://github.com/borkdominik/bigER/blob/main/webview/src/layout-postprocessor.ts), which is responsible for the layout of edge labels after model requests. In particular, it seems the client-server communication (of request model and layout model) is not working as expected. See [Client-Server Protocol Documentation](https://github.com/eclipse/sprotty/wiki/Client-Server-Protocol) in the Sprotty Wiki.

I have looked and debugged several related components, however, I was not able to pinpoint the exact code location  that is causing the issue yet. My hypothesis is that the issue is caused somewhere in the initialization process of the toolbar (see [ERDiagramWidget](https://github.com/borkdominik/bigER/blob/dd326dd44860f5b49d4921f31cd0b3471228d220/webview/src/toolbar.ts)) (e.g., through incorrect bindings).

**Comment by Aksem** [comment]
A bit more details: labels have width: 0 in bounds until changing/refreshing the diagram, half of the width is not compensated in the x-coordinate of labels, and as a result, they are in the wrong position.
I'll investigate it further and provide more information.

**Comment by Aksem** [comment]
I've got it!
The problem is that the boundaries of edge labels are not calculated on the initial loading. They are calculated only for elements that are rendered. And edge children are not rendered because the route length is 0 (see [NotationEdgeView](https://github.com/borkdominik/bigER/blob/main/webview/src/views.tsx#L112)). The route length is 0 because LibavoidRouter skips routing if boundaries are not calculated yet(see [LibavoidRouter.routeAll](https://github.com/Aksem/sprotty-routing-libavoid/blob/master/src/libavoid-router.ts#L556)).

After boundaries calculation, edges are re-rendered again, and the route length is not 0 anymore, and this is exactly the moment when edge children(labels) appear in the diagram. But boundaries are not calculated for new elements, only after refreshing/changing the diagram.

I have no straightforward solution for this problem because I need to know the expected behavior in detail. I can propose the following options:
1. Render children of edges even if the edge route is 0.
2. Try to change LibavoidRouter so that boundaries are not required, and route edges always, even before boundaries calculation.
3. Activate boundaries calculation after adding new elements if possible.
