### ISSUE TITLE
Got an incompatible VSCode error 1.31.1

### ISSUE THREAD

**Issue by mrRobot62** [borkdominik/bigER#5]
Hi, I got this error message during installing this plugin into VSCode

<img width="190" alt="image" src="https://user-images.githubusercontent.com/949032/149085050-43fcc20e-2541-47ed-b854-36e69c8fe5f8.png">

It's not so easy to update VS-Code to any other version, because we have some restrictions.

Any chance to build this plugin working on VSCode 1.31.1 ?

**Comment by mrRobot62** [comment]
perfect - thanks for this quick response !
(As I saw in source code in package.json)
    "license": "MIT",
    "engines": {
        "vscode": "^1.50.0"
    },
    
    Is it only a configuration topic or is source code involved?
    
    However thanks for your response

**Comment by plglaser** [comment]
The [new release of bigER]() is supported on VS Code **1.46.0 and above**. This is due to the underlying framework [`sprotty-vscode`](https://github.com/eclipse/sprotty-vscode/) also setting the `vscode` field in `engines` to this concrete version (see the [`package.json`](https://github.com/eclipse/sprotty-vscode/blob/master/sprotty-vscode-extension/package.json) of sprotty-vscode).
